# Generated by Django 4.2.5 on 2024-01-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_assembly_component_complage_assembly_composants"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(help_text="hex", max_length=7)),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "sphere"), ("2", "box"), ("3", "cylinder")],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
